export const AppContent = {
  brand: "Socially",
  save: "Save",
  update: "Update",
  delete: "Delete",
  cancel: "Cancel",
  ok: "Ok",
  close: "Close",
  signIn: "Sign in",
  signUp: "Sign up",
  loading: "Loading...",
  signInWait: "Please wait authenticating...",
  signUpWait: "Please wait registering...",
  dontHaveAccount: "If you don't have an account, please click on ",
  forgotPassword: "Forgot Password",
};
